Bookstore: styling
hienphan0111/bookstore pull request #7
Opened 2023-03-02 15:41 UTC by hienphan0111

This section, I have completed the following requirements:
- [ ] Add any missing JSX elements to your project (without adding extra functionality)

- [ ] Final design should match Zeplin's design (this includes all elements + the same styling)

2023-03-02 16:20 UTC, roshan-bajgain requested changes
Hi @hienphan0111, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 16:20 UTC, roshan-bajgain commented on src/components/Navbar.component.jsx
> +          </svg>
- [ ] Styling should be exactly the same provide on the [Zeplin](https://zeplin.io/). Please make sure to add the same color, font, and spacing. Please see the image below for reference.
- [ ] I would suggest you please use the credentials provided on your requirement 
### Your design
![his](https://user-images.githubusercontent.com/81727988/222482735-c988a732-624d-4393-8cae-57a22ce3064d.png)

### Original design
![original](https://user-images.githubusercontent.com/81727988/222482774-3b212714-cced-4208-b1e7-7aeb351b7023.png)

2023-03-02 16:20 UTC, roshan-bajgain commented on src/components/Book.component.jsx
>        </div>
- [ ] According to the project requirement your styling should be exactly the same as provided on the Zeplin. Please make sure to add the same color and font. Please see the image below for reference.
- [ ] Please use the same color and font provided on the design
### Your design
![his](https://user-images.githubusercontent.com/81727988/222484556-8ab54278-c13a-483f-b61a-843d749314b4.png)

### Original design
![original](https://user-images.githubusercontent.com/81727988/222484599-541a480b-695f-4b18-bd5d-5a254db14825.png)

2023-03-02 16:20 UTC, roshan-bajgain commented on src/components/Book.styles.scss
> +
- [ ] I would suggest you please make the input field matches the design. like color, font and the input is covering the whole width. Please design below for reference. Please make the color same for`Add new Book, Placeholder` 
### Your design
![his](https://user-images.githubusercontent.com/81727988/222486126-275e34a2-db5d-46f9-baa7-f69c560377ef.png)

### Original design
![original](https://user-images.githubusercontent.com/81727988/222486155-1dfa4b2c-daaa-4488-8a2c-ea512b711eb4.png)

2023-03-03 04:50 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED 👍 

Hi @hienphan0111 , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Styling exactly as the Zeplin design 
:heavy_check_mark: CSS best practices used
:heavy_check_mark: Descriptive Readme file and PR

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 06:25 UTC, merged